modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "${issue_tracker}"
license = "${mod_license}"
[[mods]]
modId = "vs_nyoom"
version = "1.20.1"
authors = ["Thea, likzerd"]

description = ''' A VS2 addon that adds various engines, thrusters and fuel system! '''

[[dependencies.vs_nyoom}]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vs_nyoom]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vs_nyoom]]
modId = "valkyrienskies"
mandatory = true
versionRange = "[${vs2_version},)"
ordering = "AFTER"
side = "BOTH"

modLoader="kotlinforforge"
loaderVersion="[4.10,)"


