modLoader = "kotlinforforge"
loaderVersion = "[4.10,)"
issueTrackerURL = "${issue_tracker}"
license = "${mod_license}"

[[mods]]
modId = "vsnyoom"
version = "0.0.1"
displayName = "VS Nyoom"
isplayURL = "${homepage}"
authors = ["likzerd, Thea"]
description = '''
${mod_description}
'''
logoFile = "icon.png"

[[dependencies.vsnyoom]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vsnyoom]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vsnyoom]]
modId = "valkyrienskies"
mandatory = true
versionRange = "[${vs2_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.vsnyoom]]
modId="kotlinforforge"
mandatory=true
versionRange="[3.12.0,)"
ordering="BEFORE"
side="BOTH"


